In [1]:
import pandas as pd
import numpy as np

In [3]:
churnData = pd.read_csv('Customer-Churn.csv')
churnData

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No,Yes,No,No,No,No,Month-to-month,29.85,29.85,No
1,Male,0,No,No,34,Yes,Yes,No,Yes,No,No,No,One year,56.95,1889.5,No
2,Male,0,No,No,2,Yes,Yes,Yes,No,No,No,No,Month-to-month,53.85,108.15,Yes
3,Male,0,No,No,45,No,Yes,No,Yes,Yes,No,No,One year,42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,No,No,No,No,No,Month-to-month,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,No,Yes,Yes,Yes,Yes,One year,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,No,Yes,Yes,No,Yes,Yes,One year,103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,Yes,No,No,No,No,No,Month-to-month,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,No,No,No,No,No,No,Month-to-month,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,Yes,No,Yes,Yes,Yes,Yes,Two year,105.65,6844.5,No

In [4]:
churnData.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [8]:
churnData['TotalCharges'] = pd.to_numeric(churnData['TotalCharges'], errors='coerce')

In [9]:
churnData.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [10]:
churnData['TotalCharges'].describe()

count    7032.000000
mean     2283.300441
std      2266.771362
min        18.800000
25%       401.450000
50%      1397.475000
75%      3794.737500
max      8684.800000
Name: TotalCharges, dtype: float64

In [11]:
churnData['tenure'].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [13]:
churnData[(churnData['tenure'] == 0) & (churnData['TotalCharges'].isna())]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,Yes,No,Yes,Yes,Yes,No,Two year,52.55,NaN,No
753,Male,0,No,Yes,0,Yes,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,20.25,NaN,No
936,Female,0,Yes,Yes,0,Yes,Yes,Yes,Yes,No,Yes,Yes,Two year,80.85,NaN,No
1082,Male,0,Yes,Yes,0,Yes,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,25.75,NaN,No
1340,Female,0,Yes,Yes,0,No,Yes,Yes,Yes,Yes,Yes,No,Two year,56.05,NaN,No
3331,Male,0,Yes,Yes,0,Yes,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,19.85,NaN,No
3826,Male,0,Yes,Yes,0,Yes,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,25.35,NaN,No
4380,Female,0,Yes,Yes,0,Yes,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,20.00,NaN,No
5218,Male,0,Yes,Yes,0,Yes,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,19.70,NaN,No
6670,Female,0,Yes,Yes,0,Yes,No,Yes,Yes,Yes,Yes,No,Two year,73.35,NaN,No
6754,Male,0,No,Yes,0,Yes,Yes,Yes,No,Yes,No,No,Two year,61.90,NaN,No

In [14]:
churnData['TotalCharges'].fillna(0, inplace=True)

C:\Users\ricki\AppData\Local\Temp\ipykernel_21072\3399307463.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  churnData['TotalCharges'].fillna(0, inplace=True)

#

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X = churnData[['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges']]
y = (churnData['Churn'] == 'Yes').astype(int)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=0)

model = LogisticRegression(random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [19]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(classification_report(y_test, y_pred, target_names=['No Churn', 'Churn']))

Accuracy: 0.7842
              precision    recall  f1-score   support

    No Churn       0.82      0.90      0.86      1041
       Churn       0.62      0.46      0.53       368

    accuracy                           0.78      1409
   macro avg       0.72      0.68      0.69      1409
weighted avg       0.77      0.78      0.77      1409

In [20]:
#imbalance check
print(churnData['Churn'].value_counts())

# With percentages
print(churnData['Churn'].value_counts(normalize=True) * 100)

Churn
No     5174
Yes    1869
Name: count, dtype: int64
Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

#

In [21]:
# separate two classes
from sklearn.utils import resample

churn_majority = churnData[churnData['Churn'] == 'No']
churn_minority = churnData[churnData['Churn'] == 'Yes']

In [22]:
# Upsampling

churn_minority_up = resample(churn_minority,
                                    replace=True,
                                    n_samples=len(churn_majority),  # match majority count
                                    random_state=0)

churn_upsampled = pd.concat([churn_majority, churn_minority_up])
print(churn_upsampled['Churn'].value_counts())

Churn
No     5174
Yes    5174
Name: count, dtype: int64

In [23]:
# Downsampling

churn_majority_down = resample(churn_majority,
                                      replace=False,                  # sample without replacement
                                      n_samples=len(churn_minority),  # match minority count
                                      random_state=0)

churn_downsampled = pd.concat([churn_majority_down, churn_minority])
print(churn_downsampled['Churn'].value_counts())

Churn
No     1869
Yes    1869
Name: count, dtype: int64

#

In [29]:
# Upsample

Xu = churn_upsampled[['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges']]
yu = (churn_upsampled['Churn'] == 'Yes').astype(int)

scaler = StandardScaler()
Xu_scaled = scaler.fit_transform(Xu)

Xu_train, Xu_test, yu_train, yu_test = train_test_split(Xu_scaled, yu, test_size=0.2, random_state=0)

model = LogisticRegression(random_state=0)
model.fit(Xu_train, yu_train)

yu_pred = model.predict(Xu_test)

In [31]:
# Downsample

Xd = churn_downsampled[['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges']]
yd = (churn_downsampled['Churn'] == 'Yes').astype(int)

scaler = StandardScaler()
Xd_scaled = scaler.fit_transform(Xd)

Xd_train, Xd_test, yd_train, yd_test = train_test_split(Xd_scaled, yd, test_size=0.2, random_state=0)

model = LogisticRegression(random_state=0)
model.fit(Xd_train, yd_train)

yd_pred = model.predict(Xd_test)

In [32]:
print("Upsample")
print(f"Accuracy: {accuracy_score(yu_test, yu_pred):}")
print(classification_report(yu_test, yu_pred, target_names=['No Churn', 'Churn']))

print("Downsample")
print(f"Accuracy: {accuracy_score(yd_test, yd_pred):}")
print(classification_report(yd_test, yd_pred, target_names=['No Churn', 'Churn']))

Upsample
Accuracy: 0.7289855072463768
              precision    recall  f1-score   support

    No Churn       0.73      0.72      0.72      1025
       Churn       0.73      0.74      0.73      1045

    accuracy                           0.73      2070
   macro avg       0.73      0.73      0.73      2070
weighted avg       0.73      0.73      0.73      2070

Downsample
Accuracy: 0.7098930481283422
              precision    recall  f1-score   support

    No Churn       0.72      0.70      0.71       374
       Churn       0.70      0.72      0.71       374

    accuracy                           0.71       748
   macro avg       0.71      0.71      0.71       748
weighted avg       0.71      0.71      0.71       748

both accuracy are lower, but churn recall are much much better